# -*- coding: utf-8 -*-
"""DeepLearning - CNN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YNjG1q6ML2cAT_zF4AFCIbI7Pv_r9XtT
"""

!pip install tensorflow tensorflow_datasets

import numpy as np
import tensorflow as tf
from tensorflow.keras import models, layers
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from PIL import Image
from google.colab import files
import tensorflow_datasets as tfds

# Upload image
uploaded = files.upload()
image_path = list(uploaded.keys())[0]

# Constants
IMG_SIZE = 128
BATCH_SIZE = 32
AUTOTUNE = tf.data.AUTOTUNE

# Load and preprocess image for prediction
img = Image.open(image_path).convert("RGB").resize((IMG_SIZE, IMG_SIZE))
img_array = tf.keras.preprocessing.image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array = preprocess_input(img_array)

plt.imshow(img)
plt.title('Uploaded Image')
plt.axis('off')
plt.show()

# Load base model
base_model = MobileNetV2(
    input_shape=(IMG_SIZE, IMG_SIZE, 3),
    include_top=False,
    weights="imagenet"
)
base_model.trainable = False

# Build model
model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(1, activation="sigmoid")
])

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

# Load dataset
(ds_train, ds_val), ds_info = tfds.load(
    "cats_vs_dogs",
    split=["train[:10%]", "train[10%:12%]"],
    as_supervised=True,
    with_info=True
)

# Dataset preprocessing
def format_img(img, label):
    img = tf.image.resize(img, (IMG_SIZE, IMG_SIZE))
    img = preprocess_input(img)
    return img, label

ds_train = (
    ds_train
    .map(format_img, num_parallel_calls=AUTOTUNE)
    .shuffle(1000)
    .batch(BATCH_SIZE)
    .prefetch(AUTOTUNE)
)

ds_val = (
    ds_val
    .map(format_img, num_parallel_calls=AUTOTUNE)
    .batch(BATCH_SIZE)
    .prefetch(AUTOTUNE)
)

# Train
model.fit(ds_train, validation_data=ds_val, epochs=5)

# Predict
prediction = model.predict(img_array)
predicted_label = "Dog" if prediction[0][0] > 0.5 else "Cat"

print("\nPrediction:", predicted_label)
print("Confidence Score:", float(prediction[0][0]))

model.summary()

